//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fyp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acceptCase
    {
        public int acceptCaseID { get; set; }
        public Nullable<int> pid { get; set; }
        public Nullable<int> did { get; set; }
        public string time { get; set; }
    
        public virtual juniorDoctor juniorDoctor { get; set; }
        public virtual patient patient { get; set; }
    }
}
