//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fyp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public int history_id { get; set; }
        public Nullable<int> patient_id { get; set; }
        public Nullable<int> jrdoc_id { get; set; }
        public string prescription { get; set; }
        public Nullable<int> rating { get; set; }
        public string date { get; set; }
        public string time { get; set; }
        public Nullable<int> status { get; set; }
    }
}
