//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fyp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class juniorDoctor
    {
        public int jrdoc_id { get; set; }
        public string full_name { get; set; }
        public string father_name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string dob { get; set; }
        public string contact { get; set; }
        public string gender { get; set; }
        public string role { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<double> rating { get; set; }
        public Nullable<int> money { get; set; }
        public Nullable<int> assignedpatientcount { get; set; }
        public Nullable<int> dailyassignedpatientcount { get; set; }
        public Nullable<System.DateTime> lastloggedindate { get; set; }
    }
}
