//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fyp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prescription
    {
        public int prescription_id { get; set; }
        public Nullable<int> appointment_id { get; set; }
        public string medicine_name { get; set; }
        public string duration { get; set; }
        public string timings { get; set; }
    }
}
