//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fyp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vital
    {
        public int vitalID { get; set; }
        public string bp { get; set; }
        public Nullable<int> sugar { get; set; }
        public Nullable<double> temper { get; set; }
        public string symptoms { get; set; }
        public string image { get; set; }
        public Nullable<int> nurseID { get; set; }
        public Nullable<int> pid { get; set; }
    }
}
