//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fyp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vital
    {
        public int vital_id { get; set; }
        public Nullable<int> patient_id { get; set; }
        public string systolic { get; set; }
        public string diastolic { get; set; }
        public string sugar { get; set; }
        public string temperature { get; set; }
        public string symptoms { get; set; }
        public string image { get; set; }
        public string testimage { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> rated { get; set; }
        public Nullable<int> appointment_id { get; set; }
    }
}
